spring:
  profiles:
    group:
      local: local, common
      prod: prod, common
    active: ${profile}

---
spring:
  config:
    activate:
      on-profile: "common"
  application:
    name: seat_sence
  sql:
    init:
      platform: mysql
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?autoReconnect=true&setTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 8
  cache:
    jcache:
      config: classpath:ehcache.xml

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
        auto: false

server:
  port: 7777
  servlet:
    context-path: /api
  forward-headers-strategy: framework

# Swagger 설정 (주소 = /api/swagger-ui/index.html)
springdoc:
  version: "v1"
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**


# jwt 설정
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: "local"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: user
      password: user!